
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// The URL and key below should match your actual Supabase project
const SUPABASE_URL = "https://zjtdwvhasntmhxsgbknf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqdGR3dmhhc250bWh4c2dia25mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDMyODksImV4cCI6MjA2MDU3OTI4OX0.nH2_TtwMz-1IqS0dazOHQPuRMxwspP_ffGuSnzr3cq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
